# 应用名称
spring:
  application:
    name: myapp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    解决sql执行查询字符编码问题,可引发中文模糊查询相关问题
    url: jdbc:mysql://192.168.111.138:3306/app?serverTimeZone=UTC&characterEncoding=UTF-8
    username: root
    password: bob463491

# 路径名称,左侧/一定要加
server:
  servlet:
    context-path: /myapp
  port: 8080
nacos:
  discovery:
    server-addr: 192.168.111.138:8848




