# 应用名称
spring:
  application:
    name: myapp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.111.138:3306/app
    username: root
    password: 123456

# 路径名称,左侧/一定要加
server:
  servlet:
    context-path: /myapp


